# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f56a6332d90da9774d52194af7e3aea75a925bffcf3721fcc380fcf8c8d33a456a8f8e2e000a669ae56fbb2c46a49c57727825539027d1b15f8a6fd83d1e522

test:
  secret_key_base: 900c6f1c2661e0027cdd11268b8bc23622716e37ce99d444b148c41b09ed510b9f6c6e7be24adfdf67bc1c37e6f2d03ca9d0084bad35f9b016d3317ac45e121f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
